apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: rogeriogeraldodev/projeto-database:1.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Senha123"
            - name: MYSQL_DATABASE
              value: "meubanco"
          volumeMounts:
            - name: mysql-dados
              mountPath: /var/lib/mysql/
      volumes:
        - name: mysql-dados
          persistentVolumeClaim:
            claimName: mysql-dados
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: rogeriogeraldodev/projeto-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
